Users Can Define Custom Palettes
ksz2k/letter_avatar pull request #15
Opened 2017-07-01 17:30 UTC by Nerdenberger

As a designer I want to ensure the colors used by letter_avatar match the color theme of my website.  To do this I need a quick way to define custom palettes for letter_avatar to use.

This PR enables users to define a custom palette in the config block and validates the custom input
```ruby 
CUSTOM_PALETTE = [ [120, 132, 205], [91, 149, 249],[72, 194, 249],[69, 208, 226]]	
LetterAvatar.setup do |config|
  config.fill_color        = 'rgba(255, 255, 255, 1)'         # default is 'rgba(255, 255, 255, 0.65)'
  config.cache_base_path   = 'testy_tars'                    # default is 'public/system'
  config.colors_palette    = :custom	                       # default is :google
  config.weight            = 500                                        # default is 300
  config.annotate_position = '-0+10'                           # default is -0+5
  config.letters_count     = 2                                        # default is 1
  config.pointsize         = 70                                        # default is 140
  config.custom_palette = CUSTOM_PALETTE        # default is nil
end
```

2017-07-01 17:32 UTC, Nerdenberger commented
@ksz2k can you take a look and let me know what you think?

2017-07-03 07:59 UTC, ksz2k requested changes
Also, please update the `README` and `CHANGELOG` for this change

2017-07-03 07:59 UTC, ksz2k commented on lib/letter_avatar/colors.rb
> +		def self.valid_custom_palette
please, use name with `?` - `valid_custom_palette?`

2017-07-03 07:59 UTC, ksz2k commented on lib/letter_avatar/configuration.rb
> +			@custom_palette = v
IMHO, `custom_palette` validation should be done here. thanks to this you'll get an exception on initialization, not when using the gem in view ;)

2017-07-11 09:35 UTC, ksz2k commented
@Nerdenberger any uptdates on this? :-)

2019-01-28 21:48 UTC, Dreamersoul commented
Can I pick this up and add the validation? This gem suits my needs and I really want a custom pallette

2019-01-29 08:09 UTC, Nerdenberger commented
Heyo,
For sure @Hamad.  I am no longer working on this unfortunately, so feel
free to pick it up.

Nick

On Tue, Jan 29, 2019 at 5:48 AM Hamad AlGhanim <notifications@github.com>
wrote:

> Can I pick this up and add the validation? This gem suits my needs and I
> really want a custom pallette
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ksz2k/letter_avatar/pull/15#issuecomment-458315011>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHahx_F04yer8SQywj3FjRFDsE5OikSMks5vH3BHgaJpZM4OLXw2>
> .
>

2019-02-05 18:17 UTC, merged